// Package main generated by 'freedom new-project godash'
package main

import (
	_ "godash/adapter/controller" //Implicit initialization controller
	_ "godash/adapter/repository" //Implicit initialization repository
	"godash/config"
	"godash/web/tmplfuncs"
	"time"

	"github.com/8treenet/freedom"
	"github.com/8treenet/freedom/infra/requests"
	"github.com/8treenet/freedom/middleware"
	"github.com/8treenet/iris/v12/view"
	"github.com/go-redis/redis"
	"gorm.io/driver/mysql"
	"gorm.io/gorm"
)

func main() {
	app := freedom.NewApplication()
	app.Iris().HandleDir("/static", "./web/static")
	viewEngine := view.HTML("./web/views", ".html").Reload(true) //如果设置为true，则重新加载模板，模板将在每次渲染时重新加载,当你在开发中并且厌倦了重新启动时，可以使用它
	tmplfuncs.Register(viewEngine)
	//viewEngine := view.HTML("./web/views", ".html")
	app.Iris().RegisterView(viewEngine)
	installMiddleware(app)
	runner := app.NewRunner(config.Get().App.Other["listen_addr"].(string))
	//app.InstallParty("/api")
	liveness(app)
	app.Run(runner, config.Get().App)
}

func installMiddleware(app freedom.Application) {
	app.InstallMiddleware(middleware.NewRecover())
	app.InstallMiddleware(middleware.NewTrace("x-request-id"))
	//One Loger per request New.
	app.InstallMiddleware(middleware.NewRequestLogger("x-request-id"))
	//The middleware output of the log line.
	app.Logger().Handle(middleware.DefaultLogRowHandle)

	//Install the Prometheus middleware.
	middle := middleware.NewClientPrometheus(config.Get().App.Other["service_name"].(string), freedom.Prometheus())
	requests.InstallMiddleware(middle)

	//HTTP request link middleware that controls the header transmission of requests.
	app.InstallBusMiddleware(middleware.NewBusFilter())
}

func installDatabase(app freedom.Application) {
	app.InstallDB(func() interface{} {
		conf := config.Get().DB
		db, err := gorm.Open(mysql.Open(conf.Addr), &gorm.Config{})
		if err != nil {
			freedom.Logger().Fatal(err.Error())
		}

		sqlDB, err := db.DB()
		if err != nil {
			freedom.Logger().Fatal(err)
		}
		if err = sqlDB.Ping(); err != nil {
			freedom.Logger().Fatal(err)
		}

		sqlDB.SetMaxIdleConns(conf.MaxIdleConns)
		sqlDB.SetMaxOpenConns(conf.MaxOpenConns)
		sqlDB.SetConnMaxLifetime(time.Duration(conf.ConnMaxLifeTime) * time.Second)
		return db
	})
}

func installRedis(app freedom.Application) {
	app.InstallRedis(func() (client redis.Cmdable) {
		cfg := config.Get().Redis
		opt := &redis.Options{
			Addr:               cfg.Addr,
			Password:           cfg.Password,
			DB:                 cfg.DB,
			MaxRetries:         cfg.MaxRetries,
			PoolSize:           cfg.PoolSize,
			ReadTimeout:        time.Duration(cfg.ReadTimeout) * time.Second,
			WriteTimeout:       time.Duration(cfg.WriteTimeout) * time.Second,
			IdleTimeout:        time.Duration(cfg.IdleTimeout) * time.Second,
			IdleCheckFrequency: time.Duration(cfg.IdleCheckFrequency) * time.Second,
			MaxConnAge:         time.Duration(cfg.MaxConnAge) * time.Second,
			PoolTimeout:        time.Duration(cfg.PoolTimeout) * time.Second,
		}
		redisClient := redis.NewClient(opt)
		if e := redisClient.Ping().Err(); e != nil {
			freedom.Logger().Fatal(e.Error())
		}
		client = redisClient
		return
	})
}

func liveness(app freedom.Application) {
	app.Iris().Get("/ping", func(ctx freedom.Context) {
		ctx.WriteString("pong123")
	})
}
